#!/bin/sh
#
# Starts Xilinx boot up scripts
#

start() {

	echo -n "Starting Xilinx Xen Boot Scripts: "
	/boot.sh
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo "Doing Nothing"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
